name: Deploy Mobile Store
on:
   push:
      branches: [ "main" ]
jobs:
   build-and-test:
      runs-on:  ubuntu-latest

      steps:
      -  name:  Checkout Code
         uses:  actions/checkout@v4

      -  name: build Docker Image
         run:
           docker build -t mobile-store-te echo "Docker Build Successful!"
